### PR TITLE
Upgrade Ruby and bundle update

### PR DESCRIPTION
**Pull request by jonallured**
This is upgrades Ruby to that latest patch so we get the security fix. While I was at it I also did a bundle update. The only one that stood out to me there was jwt, so I took a look at the CHANGELOG:

https://github.com/jwt/ruby-jwt/blob/master/CHANGELOG.md

And nothing stood out to me, but we can be sure once this hits staging and I smoke test things there.

### CODE REVIEW

**Comment by ashkan18** [comment]
oh nice! looks like `oauth2` opened up their JWT requirement 👍  merge on green

**Comment by jonallured** [comment]
Ugh, Ruby hasn't released the new images yet:

https://hub.docker.com/r/library/ruby/tags/

**Comment by ashkan18** [comment]
ooh interesting! Cutting Edge :) Looks like CircleCI is also having issues

**Comment by jonallured** [comment]
Fixed this and pushed a new commit squashing everything down into one. Once GitHub is back to working correctly, I'll make sure a build is triggered and then we can get this sucker merged.

**Comment by jonallured** [comment]
GitHub webhooks finally caught up and this is green so merging! ❤️

**Pull request merged**
