### PR TITLE
Add sort by updated_at option for orders

### PR DESCRIPTION
**Pull request by williardx**
Addresses [CP-56](https://artsyproduct.atlassian.net/browse/CP-56). Adds option to sort orders by `updated_at` in ascending/descending order.

### CODE REVIEW

**Comment by ashkan18** [comment]
hehe just noticed you did similar thing with the query part of the method! 👍

**Comment by williardx** [comment]
Hah, I just did the opposite -- makes more sense to have `validate_params!` be its own method though, I'll change it and update.

**Comment by ashkan18** [comment]
sorry looks like my PR merged caused conflicts here :(

**Comment by ashkan18** [comment]
Nice 🙌

**Pull request merged**
