### PR TITLE
[Toolchain] Add Guard for watching tests

### PR DESCRIPTION
**Pull request by damassi**
Follows [Convection PR](https://github.com/artsy/convection/pull/505) in adding `Guard`, which will watch tests for changes and re-execute, without having to restart command. Additionally adds the ability to focus on specific tests via the `focus: true` param.  

guard

### CODE REVIEW

**Comment by jonallured** [comment]
Woot! I know this PR is about the rspec watching, but I think there's a couple more things to do here to get that livereload stuff working:

https://github.com/artsy/convection/blob/master/config/environments/development.rb#L43-L45
https://github.com/artsy/convection/blob/master/Gemfile#L55

I _think_ that's it.

**Comment by damassi** [comment]
@jonallured I copied and pasted that from Convection -- what does the live-reload bit do? Rails already automatically reloads on changes, no?

**Comment by jonallured** [comment]
@damassi I don't think it does it automatically, I think the config I linked to is required but I confess that I did not actually try it on this branch so it's certainly possible I'm wrong!

**Comment by damassi** [comment]
Since this app has little to no UI, updated to remove the live-reload bits in favor of focusing specifically on guard for tests (also added a screen-cap up above).

**Comment by jonallured** [comment]
Nice one! 🐎

**Pull request merged**
