### PR TITLE
Use Simplecov and Codecov for coverage reporting

### PR DESCRIPTION
**Pull request by eessex**
- Replaces `coveralls` with `simplecov` gem, and updates reporting configuration
- Uploads reports after CI test runs via `codecov` orb

Coverage reports for this app available here: https://codecov.io/gh/artsy/exchange

Related to https://artsyproduct.atlassian.net/browse/PLATFORM-2072

### CODE REVIEW

**Comment by ashkan18** [comment]
oh nice! this def looks simpler :) thanks! we also had this issue in the past with codecov where it wasn't uploading coverage from `master` when running in circle in docker hopefully this fixes it.

**Comment by eessex** [comment]
This matches the setup we've used for CI on other apps, so I'd expect to see coverage for master once the staging deploy finishes running.

**Comment by eessex** [comment]
Looks like master is there now - https://codecov.io/gh/artsy/exchange/branches

**Comment by ashkan18** [comment]
niiiice!

**Pull request merged**
