### PR TITLE
Update order code to match expected format

### PR DESCRIPTION
**Pull request by ashkan18**
# Change
https://www.notion.so/artsy/Define-order-number-structure-65e2d9186f214b1184113a9d5a010b3b

### CODE REVIEW

**Comment by ashkan18** [comment]
yes, `id` is just `order`'s sequential auto generated id and we just pad it with zeroes and `B` at the beginning.

**Comment by williardx** [comment]
Looking at the discussion in Notion we talked about human-readable numbers being randomized. I don't know that a decision was ever finalized on that, but I would definitely lobby for randomized vs. sequential order numbers.

**Comment by ashkan18** [comment]
oh somehow i totally missed that chat icon for that item and all discussion we had, i'd say if we are going with random numbers we might be better with random characters, padded random numbers feel little strange.

**Comment by williardx** [comment]
Do they need to be padded? I.e. could we just generate a random 8-digit number in a given range?

**Comment by ashkan18** [comment]
we'd get more chances and less collisions, right? 6 digit number would ignore 0000001 as an option, i just commented on that notion chat section, im leaning more towards `B<6 random non-digits>` all caps.

**Comment by sepans** [comment]
Looks great 🥇 merging.

**Pull request merged**
