### PR TITLE
Ignores deleted artworks during inventory undeduction

### PR DESCRIPTION
**Pull request by ashfurrow**
[Discussed in Slack](https://artsy.slack.com/archives/CB110C6LE/p1546616701076600?thread_ts=1546616137.073300&cid=CB110C6LE), this PR is a follow-up to #364 and [PURCHASE-718](https://artsyproduct.atlassian.net/browse/PURCHASE-718). This PR changes calls to gravity's `inventory` endpoint to undeduct inventory (typically from a refund). If the API call fails due to a 404 (a deleted artwork) then it won't be retried. I looked for other places we call this undeduction, and I don't see any issues with not retrying.

### CODE REVIEW

**Comment by ashkan18** [comment]
Thanks for quick fix! Another alternative could be using [`discard_on`](https://api.rubyonrails.org/v5.2.1/classes/ActiveJob/Exceptions/ClassMethods.html) in the job itself, we could say 
```ruby
discard_on ErrorsValidationError do |_job, error|
  Logger.warn(...)
end
```
Looking at `undeduct` usages, your current approach should work too but i wonder if there are cases that we want to raise error in the future. We can always follow up if we needed to raise error.

**Comment by ashfurrow** [comment]
Yeah, let's move to `discard_on` to be more idiomatic/explicit. I'll switch to `Logger.warn`, too.

**Comment by ashfurrow** [comment]
I switched to `discard_on`, but let me add a test for it too.

**Comment by ashkan18** [comment]
Thanks! 🙌

**Pull request merged**
