### PR TITLE
remove Events:: namespace from OrderEvent call

### PR DESCRIPTION
**Pull request by erikdstock**
`PostNotificationJob#perform` calls `Events::OrderEvent#post`, but there is no `Events` namespace. As a result AMQP jobs are quietly retrying.

https://github.com/artsy/exchange/blob/4a38e435751b25553c5a5784a8e81ef0c48ea7ee/app/events/order_event.rb#L1

### CODE REVIEW

**Comment by joeyAghion** [comment]
Not really trivial! Could use a spec, since apparently this code isn't traversed by existing tests.

**Comment by erikdstock** [comment]
👍 - will add test.

**Comment by jonallured** [comment]
Awesome, and thanks for adding the spec!! 🏆 

merge on green

**Comment by williardx** [comment]
Thanks @erikdstock!

**Comment by jonallured** [comment]
Oh hrm, I wonder why merge on green didn't work. 🤔

**Pull request merged**
