### PR TITLE
Gem updates, mainly active-admin and stripe-mock

### PR DESCRIPTION
**Pull request by ashkan18**
# Why? Why?!?!?
As part of SCA and switching to Stripe's `payment_intent` I wanted to update `stripe_ruby_mock` but ended up doing a `bundle update` which showed we are behind on few libs, the bigger changes were:
- `activeadmin (1.3.1)` -> `2.1.0`: this meant we need to remove `.coffee` file and change to `js` since active admin has moved away from ☕️ script
- `paper_trail (10.0.1)`  -> `10.3.0`: this required updating all `has_papertrail` methods to wrap `class` in `versions: {...}`.
- `graphql (1.8.11)` -> `1.9.7`, this introduced better error messages for invalid params passed to query/mutation. Updated our tests to match new changes.

### CODE REVIEW

**Comment by sweir27** [comment]
Woooooo!

adventure_party

**Comment by sweir27** [comment]
Reran the workflow, will see if it passes.

**Comment by ashkan18** [comment]
looks like its a rubocop failure where rubocop has removed `--rails` option https://github.com/rubocop-hq/rubocop/issues/5976 going to fix it.

**Comment by ashkan18** [comment]
had to revert `puma` update because of https://github.com/puma/puma/issues/1828

**Comment by ashkan18** [comment]
@sweir27 back to 🍏 so those ice creams can be happy again

**Pull request merged**
