### PR TITLE
Remove deprecated initialOffer

### PR DESCRIPTION
**Pull request by ashkan18**
# Change
After https://github.com/artsy/metaphysics/pull/1392 we are not using `initialOffer` mutation anymore.

### CODE REVIEW

**Comment by sweir27** [comment]
Looks like this is still being used in reaction, so we'll need to remove it from [there](https://github.com/artsy/reaction/blob/master/src/Apps/Order/Routes/Offer/index.tsx#L60) first.

**Comment by ashkan18** [comment]
oh i missed this, i thought we updated MP's `initialOffer` to `addInitialOffer` here https://github.com/artsy/metaphysics/pull/1392/files#diff-64c859093a3dc429f7f188f6ea906411R33

**Comment by ashkan18** [comment]
closing for now, till we update reaction.

**Comment by ashkan18** [comment]
waiting for https://github.com/artsy/reaction/pull/1605

**Pull request closed without merging**
